import fs from "node:fs/promises";
import path from "node:path";
import OpenAI from "openai";
import sharp from "sharp";
import { publicBaseUrl } from "./env";

const OUTPUT_DIR = path.join(process.cwd(), "public", "generated", "automation");

export async function renderAutomationImage(id: string, summary: string) {
  await fs.mkdir(OUTPUT_DIR, { recursive: true });

  if (process.env.OPENAI_API_KEY && process.env.OPENAI_IMAGE_MODEL) {
    const aiImage = await tryRenderOpenAiImage(id, summary);
    if (aiImage) {
      return aiImage;
    }
  }

  const filePath = path.join(OUTPUT_DIR, `${id}.png`);
  await sharp(Buffer.from(makeSummarySvg(summary))).png().toFile(filePath);
  return {
    imagePath: filePath,
    imageUrl: `${publicBaseUrl()}/generated/automation/${id}.png`,
    usedAiImage: false,
  };
}

async function tryRenderOpenAiImage(id: string, summary: string) {
  try {
    const client = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
    const response = await client.images.generate({
      model: process.env.OPENAI_IMAGE_MODEL,
      prompt: [
        "Create a polished Japanese social media briefing image.",
        "Use clean editorial layout, readable Japanese text zones, and a professional modern style.",
        "Do not include fake logos or screenshots.",
        `Brief:\n${summary}`,
      ].join("\n"),
      size: "1024x1024",
    });
    const b64 = response.data?.[0]?.b64_json;
    if (!b64) return null;

    const filePath = path.join(OUTPUT_DIR, `${id}.png`);
    await fs.writeFile(filePath, Buffer.from(b64, "base64"));
    return {
      imagePath: filePath,
      imageUrl: `${publicBaseUrl()}/generated/automation/${id}.png`,
      usedAiImage: true,
    };
  } catch (error) {
    console.warn(
      "OpenAI image generation failed. Falling back to local renderer.",
      error instanceof Error ? error.message : "Unknown error",
    );
    return null;
  }
}

function makeSummarySvg(summary: string) {
  const lines = wrapText(summary, 34).slice(0, 20);
  const escapedLines = lines.map(escapeXml);
  const tspans = escapedLines.map((line, index) => (
    `<tspan x="86" dy="${index === 0 ? 0 : 38}">${line}</tspan>`
  )).join("");

  return `
<svg width="1200" height="1200" viewBox="0 0 1200 1200" xmlns="http://www.w3.org/2000/svg">
  <rect width="1200" height="1200" fill="#101418"/>
  <rect x="52" y="52" width="1096" height="1096" rx="28" fill="#f6f1e7"/>
  <rect x="86" y="86" width="1028" height="10" fill="#1f7a6d"/>
  <text x="86" y="164" font-family="Arial, 'Noto Sans JP', sans-serif" font-size="42" font-weight="700" fill="#17201f">Levela Trigger Brief</text>
  <text x="86" y="234" font-family="Arial, 'Noto Sans JP', sans-serif" font-size="30" font-weight="500" fill="#263331">${tspans}</text>
  <text x="86" y="1092" font-family="Arial, sans-serif" font-size="24" fill="#65706c">Generated by Levela automation</text>
</svg>`;
}

function wrapText(text: string, lineLength: number) {
  const normalized = text.replace(/\r/g, "").split("\n").flatMap((line) => {
    const chunks: string[] = [];
    let current = "";
    for (const char of line.trim()) {
      current += char;
      if (current.length >= lineLength) {
        chunks.push(current);
        current = "";
      }
    }
    if (current) chunks.push(current);
    return chunks.length ? chunks : [""];
  });
  return normalized;
}

function escapeXml(value: string) {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
